version: "3"

services:
  database:
    image: mongo
    container_name: db-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - docker:/data/db

  express:
    container_name: back-end
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      DB_LOCAL_URL: mongodb://db:27017/socket
    depends_on:
      - database
